dist: trusty
sudo: false

language: cpp

cache:
  ccache: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:lkoppel/robotics'
      - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ universe"
    packages:
      - g++-5
      - libboost-dev
      - libyaml-cpp-dev
      - libeigen3-dev
      - libpcl-dev
      - libopencv-dev
      - libceres-dev
      - libkindr-dev
      - libgeographic-dev
      - clang-format-3.8

before_script:
  - export CXX=g++-5 CC=gcc-5  # override travis defaults

script:
  - bash scripts/ci/ci_check.bash
  - bash scripts/ci/ci_run.bash

notifications:
  email: false
