# Configuration parameters for

# Norm type to use for distance calculation between feature descriptors.
#
#  Options:
#  cv::NORM_INF: l-infinity norm
#  cv::NORM_L1: l1 norm
#  cv::NORM_L2: l2 norm
#  cv::NORM_L2SQR: l2 norm, squared
#  cv::NORM_HAMMING: Hamming distance
#  cv::NORM_HAMMING2:
#
#  As per OpenCV docs, NORM_L1 and NORM_L2 is valid for the SIFT or
#  SURF descriptors, while NORM_HAMMING is valid for the ORB, BRISK, and
#  BRIEF descriptors. NORM_HAMMING2 should only be used with ORB, when
#  WTA_K is 3 or 4.
#
#  Default: NORM_HAMMING, since currently only BRISK Descriptor is used.
#
#  Please refer to further description of the norm types
#  [here][opencv_norm_types].
#
#  [opencv_norm_types]:
#  http://docs.opencv.org/trunk/d2/de8/group__core__array.html#gad12cefbcb5291cf958a85b4b67b6149f
#
norm_type: cv::NORM_HAMMING

# This boolean enables or disables the cross-checking functionality, which
# looks to remove false matches. If true, the closest match to
# descriptor_1 from descriptor_2 will only be reported if the object in
# descriptor_2 is also the closest to descriptor_1.
#
# Recommended: false
cross_check: false
